import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { LiveReviewCount } from "@/components/GoogleReviewStats";
import { PremiumPaintStory } from "@/components/PremiumPaintStory";
import { TrackedLink } from "@/components/TrackedLink";
import { WorkGallery } from "@/components/WorkGallery";
import { FaqList } from "@/components/FaqList";
import { JsonLd } from "@/components/JsonLd";
import { paintFaqs } from "@/data/faqs";
import { ceramicDoes, ceramicDoesNot, paintServices } from "@/data/paint";
import { usd } from "@/lib/format";
import { pageMetadata, serviceSchema } from "@/lib/seo";
export const metadata=pageMetadata({title:"Ceramic Coating in Decatur & Atlanta, GA | Every Detail",description:"Professional 2-year ceramic coating with paint correction included, from $895. Mobile ceramic coating service in Decatur and Atlanta.",path:"/ceramic"});
const quote="/get-a-quote?interest=ceramic";
export default function CeramicPage(){const ceramic=paintServices[2];return <>
<section className="paint-service-hero ceramic-hero text-paper"><div className="paint-service-hero-bg"/><div className="paint-service-hero-overlay"/><div className="container-ed paint-service-hero-inner"><Breadcrumbs items={[{name:"Ceramic Coating",path:"/ceramic"}]}/><div className="paint-service-hero-copy"><p className="eyebrow">2-year ceramic coating · Decatur + Atlanta</p><h1>Protect the finish<br/><span>worth keeping.</span></h1><p>We prepare and correct the paint first, then apply professional ceramic protection designed to keep the finish glossier, slicker and easier to maintain.</p><div className="paint-hero-actions"><TrackedLink href={quote} event="paint_inquiry" params={{location:"ceramic_hero"}} className="btn btn-primary">Get my coating quote ↗</TrackedLink><a href="#coating-package" className="btn btn-outline-on-dark">See what’s included</a></div><div className="paint-hero-proof"><span><strong><LiveReviewCount/></strong> five-star reviews</span><span>2-year protection</span><span>Correction included</span></div></div></div></section>
<PremiumPaintStory variant="ceramic"/>
<section className="paint-proof-strip"><div className="container-ed"><div className="paint-proof-head"><div><p className="eyebrow">The finished product</p><h2 className="t-h2">Protection should look this good.</h2></div><p>The coating matters, but the prep underneath it is what separates a protected car from a properly finished one.</p></div><WorkGallery ids={["ceramic-01","ceramic-02","paint-01","paint-03"]}/></div></section>
<section id="coating-package" className="coating-package"><div className="container-ed coating-package-grid"><div className="coating-package-lead"><p className="eyebrow">One complete coating service</p><h2>We don’t coat over<br/><span>bad paint.</span></h2><p>{ceramic.summary}</p><Link href="/paint-correction" className="link">Only need correction? See paint correction ↗</Link></div><article className="coating-ticket"><div className="coating-ticket-top"><span>EVERY DETAIL / PAINT CARE</span><span>02 YEAR</span></div><h3>{ceramic.name}</h3><p className="coating-price"><small>starting at</small>{usd(ceramic.startingAt)}</p><ul>{ceramic.includes.map((x,i)=><li key={x}><b>0{i+1}</b><span>{x}</span></li>)}</ul><TrackedLink href={quote} event="paint_inquiry" params={{location:"ceramic_package"}} className="btn btn-primary">Get my coating quote</TrackedLink><p className="coating-ticket-note">Final price is confirmed after we see the vehicle and paint condition.</p></article></div></section>
<section className="ceramic-truth"><div className="container-ed"><p className="eyebrow">No coating mythology</p><h2>What ceramic does.<br/><span>And what it doesn’t.</span></h2><div className="ceramic-truth-grid"><div><h3>YES</h3>{ceramicDoes.map(x=><p key={x}>{x}</p>)}</div><div><h3>NO</h3>{ceramicDoesNot.map(x=><p key={x}>{x}</p>)}</div></div></div></section>
<section className="coating-maintenance"><div className="container-ed coating-maintenance-grid"><div><p className="eyebrow">Living with a coating</p><h2>Easier to maintain.<br/>Not maintenance-free.</h2></div><div><p>A coated car still needs proper washing. Use pH-neutral soap and clean microfiber, and avoid automatic brush washes that can mar any clear coat.</p><p>Your 2-year coating includes a free follow-up detail. After that, our Maintenance Detail or Detail+ can keep the finish cared for without turning ownership into a project.</p><Link href="/detailplus" className="link">See Detail+ maintenance ↗</Link></div></div></section>
<section className="border-t border-line bg-paper2 py-16 md:py-24"><div className="container-ed grid gap-10 lg:grid-cols-12"><h2 className="t-h2 lg:col-span-4">Ceramic coating questions</h2><div className="lg:col-span-8"><FaqList faqs={paintFaqs}/></div></div></section>
<section className="bg-oxblood text-paper"><div className="container-ed paint-final-cta"><div><p className="eyebrow">Correct. Coat. Maintain.</p><h2>Start with the paint you have.</h2><p>Tell us what you drive and what you want from the finish. We’ll confirm whether coating makes sense and what preparation the paint needs first.</p></div><TrackedLink href={quote} event="paint_inquiry" params={{location:"ceramic_final"}} className="btn btn-on-dark">Get my coating quote</TrackedLink></div></section>
<JsonLd data={serviceSchema({name:"2-Year Ceramic Coating",description:ceramic.summary,path:"/ceramic",lowPrice:ceramic.startingAt})}/></>}
