import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { LiveReviewCount } from "@/components/GoogleReviewStats";
import { PremiumPaintStory } from "@/components/PremiumPaintStory";
import { TrackedLink } from "@/components/TrackedLink";
import { WorkGallery } from "@/components/WorkGallery";
import { FaqList } from "@/components/FaqList";
import { JsonLd } from "@/components/JsonLd";
import { paintFaqs } from "@/data/faqs";
import { paintDefects, paintServices } from "@/data/paint";
import { site } from "@/data/site";
import { usd } from "@/lib/format";
import { pageMetadata, serviceSchema } from "@/lib/seo";
export const metadata=pageMetadata({title:"Paint Correction in Decatur & Atlanta, GA | Every Detail",description:"Professional mobile paint correction in Decatur and Atlanta. Enhancement polishing from $395 and full multi-stage correction from $695.",path:"/paint-correction"});
const quote="/get-a-quote?interest=paint-correction";
export default function PaintCorrectionPage(){const [enhancement,correction]=paintServices;return <>
<section className="paint-service-hero correction-hero text-paper"><div className="paint-service-hero-bg"/><div className="paint-service-hero-overlay"/><div className="container-ed paint-service-hero-inner"><Breadcrumbs items={[{name:"Paint Correction",path:"/paint-correction"}]}/><div className="paint-service-hero-copy"><p className="eyebrow">Paint correction · Decatur + Atlanta</p><h1>Bring the <span>paint</span><br/>back.</h1><p>Swirls, haze and wash marks steal clarity from otherwise good paint. We machine-polish the clear coat to remove defects and restore the finish itself.</p><div className="paint-hero-actions"><TrackedLink href={quote} event="paint_inquiry" params={{location:"correction_hero"}} className="btn btn-primary">Get my correction quote ↗</TrackedLink><a href="#correction-options" className="btn btn-outline-on-dark">See options</a></div><div className="paint-hero-proof"><span><strong><LiveReviewCount/></strong> five-star reviews</span><span>Mobile service</span><span>From {usd(enhancement.startingAt)}</span></div></div></div></section>
<PremiumPaintStory variant="correction"/>
<section className="paint-proof-strip"><div className="container-ed"><div className="paint-proof-head"><div><p className="eyebrow">Real paint. Real work.</p><h2 className="t-h2">Clarity you can see in the reflections.</h2></div><p>No stock correction photos. This is the kind of finish our team is working toward on actual client cars.</p></div><WorkGallery ids={["paint-01","paint-02","paint-03","ceramic-01"]}/></div></section>
<section id="correction-options" className="container-ed paint-choice-section"><p className="eyebrow">Choose the level</p><h2 className="paint-choice-title">Not every car needs<br/><span>the same correction.</span></h2><div className="paint-choice-grid">{[enhancement,correction].map((p,i)=><article className={`paint-choice-card ${i===1?"featured":""}`} key={p.id}><div className="paint-choice-number">0{i+1}</div><p className="eyebrow">{i===0?"REFINE":"RESET THE FINISH"}</p><h3>{p.name}</h3><p className="paint-choice-price">from <strong>{usd(p.startingAt)}</strong></p><p>{p.summary}</p><div className="paint-choice-best"><b>Best for</b><span>{p.bestFor}</span></div><ul>{p.includes.map(x=><li key={x}>{x}</li>)}</ul><TrackedLink href={quote} event="paint_inquiry" params={{location:`correction_${p.id}`}} className={i===1?"btn btn-primary":"btn btn-secondary"}>Get a quote</TrackedLink></article>)}</div></section>
<section className="paint-editorial"><div className="container-ed paint-editorial-grid"><div><p className="eyebrow">What we’re actually fixing</p><h2>Those circles around the sun aren’t dirt.</h2></div><div>{paintDefects.map((d,i)=><div className="paint-defect" key={d.name}><span>0{i+1}</span><div><h3>{d.name}</h3><p>{d.detail}</p></div></div>)}</div></div></section>
<section className="paint-cross-sell"><div className="container-ed"><p className="eyebrow">After correction</p><h2>You fixed the paint.<br/><span>Now you can keep it that way.</span></h2><p>Ceramic coating adds long-term protection over a properly prepared finish. If protection is the goal from the start, go straight to the coating service.</p><Link href="/ceramic" className="btn btn-on-dark">Explore ceramic coating ↗</Link></div></section>
<section className="container-ed py-16 md:py-24"><div className="grid gap-10 lg:grid-cols-12"><h2 className="t-h2 lg:col-span-4">Paint correction questions</h2><div className="lg:col-span-8"><FaqList faqs={paintFaqs}/></div></div></section>
<section className="bg-oxblood text-paper"><div className="container-ed paint-final-cta"><div><p className="eyebrow">Your paint, evaluated honestly.</p><h2>Show us what you’re seeing.</h2><p>Tell us about the car and the condition. We’ll recommend the right level of correction instead of automatically selling the biggest package.</p></div><TrackedLink href={quote} event="paint_inquiry" params={{location:"correction_final"}} className="btn btn-on-dark">Get my paint quote</TrackedLink></div></section>
<JsonLd data={[enhancement,correction].map(p=>serviceSchema({name:p.name,description:p.summary,path:"/paint-correction",lowPrice:p.startingAt}))}/></>}
